# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 17:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id_account', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(default='Example University', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id_org', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('org_FullName', models.CharField(max_length=100)),
                ('org_ShortName', models.CharField(max_length=20)),
                ('org_type', models.CharField(choices=[('U', 'University'), ('S', 'School or College'), ('D', 'Department'), ('O', 'Office'), ('L', 'Class or lecture'), ('E', 'Class or lecture section'), ('G', 'Group')], default='G', max_length=1)),
                ('org_HasParent', models.BooleanField(default=False)),
                ('id_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allonsy_main.Account')),
            ],
        ),
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('id_user', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('user_name_alias', models.CharField(max_length=100)),
                ('user_country_id', models.CharField(default='US', max_length=2)),
                ('user_city_name', models.CharField(max_length=100)),
                ('user_province_name', models.CharField(max_length=100)),
                ('user_postal_code', models.CharField(max_length=10)),
                ('user_home_street_number', models.CharField(max_length=100)),
                ('user_home_street_name', models.CharField(max_length=100)),
                ('user_home_ApartmentNumber', models.CharField(max_length=16)),
                ('user_phone_CountryCode', models.IntegerField(max_length=3)),
                ('user_phone_value', models.IntegerField(max_length=10)),
                ('user_phone_home_CountryCode', models.IntegerField(max_length=3)),
                ('user_phone_home_value', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RelationsMeepleOnCampusResidence',
            fields=[
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='allonsy_main.UserExtension')),
                ('id_period', models.CharField(max_length=100)),
                ('id_residence', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='userextension',
            name='id_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allonsy_main.Account'),
        ),
        migrations.AddField(
            model_name='userextension',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
