# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='user_phone_CountryCode',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='user_phone_home_CountryCode',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='user_phone_home_value',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='user_phone_value',
            field=models.CharField(max_length=10),
        ),
    ]
