# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-12 18:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allonsy_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteractionTree',
            fields=[
                ('uuid_interaction', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_status', models.CharField(choices=[('O', 'New interaction'), ('I', 'Reviewed interaction'), ('X', 'Deleted interaction'), ('B', 'Blocked interaction'), ('F', 'Flagged as inappropriate')], default='O', max_length=1)),
                ('interaction_type', models.CharField(choices=[('C', 'Connection request'), ('R', 'Roommate request'), ('M', 'Message')], default='M', max_length=1)),
                ('interaction_subject', models.CharField(default='New message', max_length=100)),
                ('interaction_text', models.CharField(default='Hello!', max_length=1000)),
                ('uuid_previous_msg', models.UUIDField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('interaction_sender', models.ManyToManyField(related_name='interaction_sender', to=settings.AUTH_USER_MODEL)),
                ('interaction_target', models.ManyToManyField(related_name='interaction_target', to=settings.AUTH_USER_MODEL)),
                ('uuid_request', models.ManyToManyField(blank=True, to='allonsy_main.RelationUserConnection')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='userinteraction',
            name='interaction_sender',
        ),
        migrations.RemoveField(
            model_name='userinteraction',
            name='interaction_target',
        ),
        migrations.RemoveField(
            model_name='userinteraction',
            name='uuid_request',
        ),
        migrations.DeleteModel(
            name='UserInteraction',
        ),
    ]
