# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-08 15:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allonsy_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationuserconnection',
            name='relation_type',
            field=models.CharField(choices=[('L', 'Personal connection'), ('M', 'Roommate connection')], max_length=1),
        ),
        migrations.RemoveField(
            model_name='relationuserconnection',
            name='uuid_user_1',
        ),
        migrations.AddField(
            model_name='relationuserconnection',
            name='uuid_user_1',
            field=models.ManyToManyField(related_name='uuid_user_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='relationuserconnection',
            name='uuid_user_2',
        ),
        migrations.AddField(
            model_name='relationuserconnection',
            name='uuid_user_2',
            field=models.ManyToManyField(related_name='uuid_user_2', to=settings.AUTH_USER_MODEL),
        ),
    ]
