# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 20:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0002_auto_20160122_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epoch',
            fields=[
                ('id_epoch', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('epoch_Name', models.CharField(max_length=100)),
                ('epoch_StartDate', models.DateField()),
                ('epoch_EndDate', models.DateField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id_location', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('location_HasParent', models.BooleanField(default=True)),
                ('location_InheritGeoFromParent', models.BooleanField(default=True)),
                ('location_type', models.CharField(choices=[('C', 'Campus'), ('V', 'Village'), ('B', 'Building'), ('F', 'Floor'), ('S', 'Suite'), ('R', 'Room'), ('L', 'Location')], max_length=1)),
                ('location_SubLocIdent', models.CharField(default='TESTING', max_length=16)),
                ('location_FullName', models.CharField(default='TESTING', max_length=100)),
                ('location_ShortName', models.CharField(default='TESTING', max_length=32)),
                ('location_abbreviation', models.CharField(default='TESTING', max_length=8)),
                ('location_country_id', models.CharField(default='US', max_length=2)),
                ('location_province_name', models.CharField(default='TESTING', max_length=100)),
                ('location_city_name', models.CharField(default='TESTING', max_length=100)),
                ('location_PostalCode', models.CharField(default='TESTING', max_length=10)),
                ('location_street_number', models.CharField(default='TESTING', max_length=100)),
                ('location_street_name', models.CharField(default='TESTING', max_length=100)),
                ('location_ApartmentNumber', models.CharField(default='TESTING', max_length=16)),
                ('location_CountryCode', models.CharField(default='555', max_length=3)),
                ('location_phone_value', models.CharField(default='TESTING', max_length=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelationLocationOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_org_child', models.PositiveIntegerField()),
                ('id_location_parent', models.PositiveIntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelationLocationTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_location_child', models.PositiveIntegerField()),
                ('id_location_parent', models.PositiveIntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelationLocationUserTransact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_now', models.DateTimeField(auto_now_add=True)),
                ('id_location_parent', models.PositiveIntegerField()),
                ('id_user_child', models.PositiveIntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelationOrganizationTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_org_child', models.PositiveIntegerField()),
                ('id_org_parent', models.PositiveIntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelationOrganizationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user_child', models.PositiveIntegerField()),
                ('id_org_parent', models.PositiveIntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelationUserLocationStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user_parent', models.PositiveIntegerField()),
                ('id_location_child', models.PositiveIntegerField()),
                ('id_epoch_child', models.PositiveIntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userextension',
            name='user_postal_code',
        ),
        migrations.AddField(
            model_name='account',
            name='account_billing_ApartmentNumber',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='account',
            name='account_billing_CountryCode',
            field=models.CharField(default='555', max_length=3),
        ),
        migrations.AddField(
            model_name='account',
            name='account_billing_PostalCode',
            field=models.CharField(default='TESTING', max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='account_billing_attn',
            field=models.CharField(default='TESTING', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='account_billing_city_name',
            field=models.CharField(default='TESTING', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='account_billing_country_id',
            field=models.CharField(default='US', max_length=2),
        ),
        migrations.AddField(
            model_name='account',
            name='account_billing_phone_value',
            field=models.CharField(default='TESTING', max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='account_billing_province_name',
            field=models.CharField(default='TESTING', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='account_billing_street_name',
            field=models.CharField(default='TESTING', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='account_billing_street_number',
            field=models.CharField(default='TESTING', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='account_billing_title',
            field=models.CharField(default='TESTING', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='account_institution_name',
            field=models.CharField(default='Example University', max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 25, 20, 19, 21, 766195, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='date_edited',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 25, 20, 19, 25, 747886, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 25, 20, 19, 30, 731546, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='date_edited',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 25, 20, 19, 37, 430349, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='org_abbreviation',
            field=models.CharField(default='TESTING', max_length=8),
        ),
        migrations.AddField(
            model_name='relationsmeepleoncampusresidence',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 25, 20, 19, 42, 775386, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationsmeepleoncampusresidence',
            name='date_edited',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 25, 20, 19, 51, 444929, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userextension',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 25, 20, 19, 55, 997958, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userextension',
            name='date_edited',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 25, 20, 20, 1, 329155, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userextension',
            name='user_PostalCode',
            field=models.CharField(default='TESTING', max_length=10),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_FullName',
            field=models.CharField(default='TESTING', max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_HasParent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_ShortName',
            field=models.CharField(default='TESTING', max_length=32),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='user_city_name',
            field=models.CharField(default='TESTING', max_length=100),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='user_home_ApartmentNumber',
            field=models.CharField(default='TESTING', max_length=16),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='user_home_street_name',
            field=models.CharField(default='TESTING', max_length=100),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='user_home_street_number',
            field=models.CharField(default='TESTING', max_length=100),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='user_name_alias',
            field=models.CharField(default='TESTING', max_length=100),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='user_phone_CountryCode',
            field=models.CharField(default='555', max_length=3),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='user_phone_home_CountryCode',
            field=models.CharField(default='555', max_length=3),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='user_phone_home_value',
            field=models.CharField(default='TESTING', max_length=10),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='user_phone_value',
            field=models.CharField(default='TESTING', max_length=10),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='user_province_name',
            field=models.CharField(default='TESTING', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='relationuserlocationstatic',
            unique_together=set([('id_user_parent', 'id_location_child', 'id_epoch_child')]),
        ),
        migrations.AddField(
            model_name='location',
            name='id_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allonsy_main.Account'),
        ),
        migrations.AddField(
            model_name='epoch',
            name='id_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allonsy_main.Account'),
        ),
    ]
