# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 00:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0003_auto_20160125_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationsmeepleoncampusresidence',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='account',
            name='id_account',
        ),
        migrations.RemoveField(
            model_name='epoch',
            name='id_account',
        ),
        migrations.RemoveField(
            model_name='epoch',
            name='id_epoch',
        ),
        migrations.RemoveField(
            model_name='location',
            name='id_account',
        ),
        migrations.RemoveField(
            model_name='location',
            name='id_location',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='id_account',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='id_org',
        ),
        migrations.RemoveField(
            model_name='relationlocationorganization',
            name='id_location_parent',
        ),
        migrations.RemoveField(
            model_name='relationlocationorganization',
            name='id_org_child',
        ),
        migrations.RemoveField(
            model_name='relationlocationtree',
            name='id_location_child',
        ),
        migrations.RemoveField(
            model_name='relationlocationtree',
            name='id_location_parent',
        ),
        migrations.RemoveField(
            model_name='relationlocationusertransact',
            name='id_location_parent',
        ),
        migrations.RemoveField(
            model_name='relationlocationusertransact',
            name='id_user_child',
        ),
        migrations.RemoveField(
            model_name='relationlocationusertransact',
            name='time_now',
        ),
        migrations.RemoveField(
            model_name='relationorganizationtree',
            name='id_org_child',
        ),
        migrations.RemoveField(
            model_name='relationorganizationtree',
            name='id_org_parent',
        ),
        migrations.RemoveField(
            model_name='relationorganizationuser',
            name='id_org_parent',
        ),
        migrations.RemoveField(
            model_name='relationorganizationuser',
            name='id_user_child',
        ),
        migrations.RemoveField(
            model_name='userextension',
            name='id_account',
        ),
        migrations.RemoveField(
            model_name='userextension',
            name='id_user',
        ),
        migrations.AddField(
            model_name='account',
            name='uuid_account',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='epoch',
            name='uuid_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='allonsy_main.Account'),
        ),
        migrations.AddField(
            model_name='epoch',
            name='uuid_epoch',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='location',
            name='uuid_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='allonsy_main.Account'),
        ),
        migrations.AddField(
            model_name='location',
            name='uuid_location',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='uuid_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='allonsy_main.Account'),
        ),
        migrations.AddField(
            model_name='organization',
            name='uuid_org',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='relationlocationorganization',
            name='uuid_location_parent',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='relationlocationorganization',
            name='uuid_org_child',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='relationlocationtree',
            name='uuid_location_child',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='relationlocationtree',
            name='uuid_location_parent',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='relationlocationusertransact',
            name='transaction_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 26, 0, 35, 52, 490039, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationlocationusertransact',
            name='uuid_location_parent',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='relationlocationusertransact',
            name='uuid_user_child',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='relationorganizationtree',
            name='uuid_org_child',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='relationorganizationtree',
            name='uuid_org_parent',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='relationorganizationuser',
            name='uuid_org_parent',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='relationorganizationuser',
            name='uuid_user_child',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='relationuserlocationstatic',
            name='uuid_epoch_child',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='relationuserlocationstatic',
            name='uuid_location_child',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='relationuserlocationstatic',
            name='uuid_user_parent',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userextension',
            name='uuid_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='allonsy_main.Account'),
        ),
        migrations.AddField(
            model_name='userextension',
            name='uuid_user',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='relationuserlocationstatic',
            unique_together=set([('uuid_user_parent', 'uuid_location_child', 'uuid_epoch_child')]),
        ),
        migrations.DeleteModel(
            name='RelationsMeepleOnCampusResidence',
        ),
    ]
