# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-08 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0003_auto_20160708_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationuserconnection',
            name='relation_status',
            field=models.CharField(choices=[('A', 'Active connection'), ('P', 'Pending connection'), ('R', 'Rejected connection'), ('D', 'Dropped connection')], max_length=255),
        ),
    ]
