# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-12 18:38
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0003_auto_20160712_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinteractiontree',
            name='message_parent',
        ),
        migrations.AddField(
            model_name='userinteractiontree',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='allonsy_main.UserInteractionTree'),
        ),
    ]
