# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 00:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0004_auto_20160125_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationuserlocationstatic',
            name='id_epoch_child',
        ),
        migrations.RemoveField(
            model_name='relationuserlocationstatic',
            name='id_location_child',
        ),
        migrations.RemoveField(
            model_name='relationuserlocationstatic',
            name='id_user_parent',
        ),
        migrations.AlterField(
            model_name='epoch',
            name='uuid_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allonsy_main.Account'),
        ),
        migrations.AlterField(
            model_name='location',
            name='uuid_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allonsy_main.Account'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='uuid_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allonsy_main.Account'),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userextension',
            name='uuid_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allonsy_main.Account'),
        ),
    ]
