# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-01 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0004_auto_20160712_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowItemTree',
            fields=[
                ('uuid_wf_item', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('wf_item_name', models.CharField(default=models.UUIDField(editable=False, primary_key=True, serialize=False), max_length=64)),
                ('wf_item_type', models.CharField(choices=[('S', 'Workflow Set'), ('I', 'Workflow Item'), ('T', 'Item body text')], default='S', max_length=1)),
                ('wf_item_is_active', models.BooleanField(default=True)),
                ('wf_item_text', models.CharField(blank=True, max_length=256)),
                ('wf_set_is_type', models.CharField(choices=[('X', 'No group set'), ('N', 'Nightly rounds'), ('D', 'On-call duty'), ('I', 'Room check-in'), ('O', 'Room check-out')], default='X', max_length=1)),
                ('wf_set_is_default_parent_for_type', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='allonsy_main.WorkflowItemTree')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
