# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-08 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0004_auto_20160708_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationuserconnection',
            name='uuid_user_1',
        ),
        migrations.RemoveField(
            model_name='relationuserconnection',
            name='uuid_user_2',
        ),
        migrations.DeleteModel(
            name='RelationUserConnection',
        ),
    ]
