# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-01 18:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allonsy_main', '0005_workflowitemtree'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationWorkflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_relation', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('wf_disp_order', models.CharField(default='1', max_length=2)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelationWorkflowUserInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_relation', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('uuid_wf_instance', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user_instance_nme', models.CharField(default='New form', max_length=256)),
                ('user_instance_state', models.CharField(choices=[('C', 'Created'), ('I', 'Edited and saved'), ('S', 'Submitted for review'), ('R', 'Reverted for edit'), ('A', 'Approved'), ('O', 'Saved as complete')], default='C', max_length=1)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('uuid_wf_edited_user', models.ManyToManyField(related_name='edited_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelationWorkflowUserItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_relation', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user_item_state', models.CharField(default='Off', max_length=16)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('uuid_wf_instance', models.ManyToManyField(related_name='instance', to='allonsy_main.RelationWorkflowUserInstance')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_wf_item', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('wf_item_is_active', models.BooleanField(default=True)),
                ('wf_item_name', models.CharField(default=models.UUIDField(default=uuid.uuid4, editable=False), max_length=64)),
                ('wf_item_text', models.CharField(blank=True, max_length=256)),
                ('wf_item_disp_order', models.CharField(default='1', max_length=2)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_wf_set', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('wf_set_name', models.CharField(default=models.UUIDField(default=uuid.uuid4, editable=False), max_length=64)),
                ('wf_set_is_type', models.CharField(choices=[('X', 'No group set'), ('N', 'Nightly rounds'), ('D', 'On-call duty'), ('I', 'Room check-in'), ('O', 'Room check-out')], default='X', max_length=1)),
                ('wf_set_is_default_parent_for_type', models.BooleanField(default=False)),
                ('wf_set_has_child', models.BooleanField(default=False)),
                ('wf_set_is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='workflowitemtree',
            name='parent',
        ),
        migrations.DeleteModel(
            name='WorkflowItemTree',
        ),
        migrations.AddField(
            model_name='workflowitem',
            name='wf_item_parent_wfset',
            field=models.ManyToManyField(blank=True, to='allonsy_main.WorkflowSet'),
        ),
        migrations.AddField(
            model_name='relationworkflowuseritems',
            name='uuid_wf_item',
            field=models.ManyToManyField(related_name='item', to='allonsy_main.WorkflowItem'),
        ),
        migrations.AddField(
            model_name='relationworkflowuserinstance',
            name='uuid_wf_set',
            field=models.ManyToManyField(related_name='set', to='allonsy_main.WorkflowSet'),
        ),
        migrations.AddField(
            model_name='relationworkflowuserinstance',
            name='uuid_wf_user',
            field=models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relationworkflow',
            name='wf_child',
            field=models.ManyToManyField(related_name='wf_child', to='allonsy_main.WorkflowSet'),
        ),
        migrations.AddField(
            model_name='relationworkflow',
            name='wf_parent',
            field=models.ManyToManyField(related_name='wf_parent', to='allonsy_main.WorkflowSet'),
        ),
    ]
