# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0005_auto_20160125_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='allonsy_main.TreeLocation')),
                ('uuid_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allonsy_main.Account')),
                ('uuid_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allonsy_main.Location')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TreeOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='allonsy_main.TreeOrganization')),
                ('uuid_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allonsy_main.Account')),
                ('uuid_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allonsy_main.Organization')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TreeOrganizationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='allonsy_main.TreeOrganizationUser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allonsy_main.UserExtension')),
                ('uuid_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allonsy_main.Account')),
                ('uuid_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allonsy_main.Organization')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
