# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-08 17:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allonsy_main', '0005_auto_20160708_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationUserConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('L', 'Personal connection'), ('M', 'Roommate connection')], max_length=1)),
                ('relation_status', models.CharField(choices=[('A', 'Active connection'), ('P', 'Pending connection'), ('R', 'Rejected connection'), ('D', 'Dropped connection')], max_length=1)),
                ('relation_expires', models.DateTimeField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('uuid_user_1', models.ManyToManyField(related_name='uuid_user_1', to=settings.AUTH_USER_MODEL)),
                ('uuid_user_2', models.ManyToManyField(related_name='uuid_user_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
