# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0006_treelocation_treeorganization_treeorganizationuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeorganization',
            name='relation_name',
            field=models.CharField(default='Test', max_length=100),
        ),
    ]
