# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-01 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0006_auto_20160801_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationworkflow',
            name='wf_child',
            field=models.ManyToManyField(blank=True, related_name='wf_child', to='allonsy_main.WorkflowSet'),
        ),
        migrations.AlterField(
            model_name='relationworkflow',
            name='wf_parent',
            field=models.ManyToManyField(blank=True, related_name='wf_parent', to='allonsy_main.WorkflowSet'),
        ),
    ]
