# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-08 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0006_relationuserconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationuserconnection',
            name='relation_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relationuserconnection',
            name='relation_status',
            field=models.CharField(choices=[('A', 'Active connection'), ('P', 'Pending connection'), ('R', 'Rejected connection'), ('D', 'Dropped connection')], max_length=255),
        ),
        migrations.AlterField(
            model_name='relationuserconnection',
            name='relation_type',
            field=models.CharField(choices=[('L', 'Personal connection'), ('M', 'Roommate connection')], max_length=255),
        ),
    ]
