# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0007_treeorganization_relation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeorganization',
            name='uuid_org',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='allonsy_main.Organization'),
        ),
    ]
