# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-08 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0007_auto_20160708_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinteraction',
            name='uuid_request',
            field=models.ManyToManyField(blank=True, null=True, to='allonsy_main.RelationUserConnection'),
        ),
    ]
