# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-03 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0007_auto_20160801_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_doc', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('uuid_doc_instance', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('wf_parent_set_name', models.CharField(max_length=64)),
                ('wf_sub_parent_set_name', models.CharField(max_length=64)),
                ('wf_item_sub_parent_disp_order', models.CharField(default='1', max_length=2)),
                ('wf_item_name', models.CharField(max_length=64)),
                ('wf_item_text', models.CharField(blank=True, max_length=256)),
                ('user_item_state', models.CharField(default='Off', max_length=16)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('wf_item_root_parent', models.ManyToManyField(related_name='root_parent', to='allonsy_main.WorkflowSet')),
                ('wf_item_sub_parent', models.ManyToManyField(related_name='immediate_parent', to='allonsy_main.WorkflowSet')),
            ],
        ),
        migrations.DeleteModel(
            name='RelationWorkflowUserItems',
        ),
    ]
