# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-13 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0008_auto_20160307_1254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelationOrganizationTree',
        ),
        migrations.RemoveField(
            model_name='treeorganizationuser',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='treeorganizationuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='treeorganizationuser',
            name='uuid_account',
        ),
        migrations.RemoveField(
            model_name='treeorganizationuser',
            name='uuid_org',
        ),
        migrations.RemoveField(
            model_name='relationorganizationuser',
            name='uuid_org_parent',
        ),
        migrations.RemoveField(
            model_name='relationorganizationuser',
            name='uuid_user_child',
        ),
        migrations.AddField(
            model_name='relationorganizationuser',
            name='relation_name',
            field=models.CharField(default='Test', max_length=100),
        ),
        migrations.AddField(
            model_name='relationorganizationuser',
            name='uuid_account',
            field=models.ForeignKey(default='4fd68e5e-3164-4420-8e7d-7d01b269be42', on_delete=django.db.models.deletion.CASCADE, to='allonsy_main.Account'),
        ),
        migrations.AddField(
            model_name='relationorganizationuser',
            name='uuid_org',
            field=models.CharField(default='4fd68e5e-3164-4420-8e7d-7d01b269be42', max_length=100),
        ),
        migrations.AddField(
            model_name='relationorganizationuser',
            name='uuid_user',
            field=models.CharField(default='4fd68e5e-3164-4420-8e7d-7d01b269be42', max_length=100),
        ),
        migrations.DeleteModel(
            name='TreeOrganizationUser',
        ),
    ]
