# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-03 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0008_auto_20160802_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowitem',
            name='wf_item_name',
        ),
    ]
