# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-03 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0009_remove_workflowitem_wf_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowitem',
            name='wf_item_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
