# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-13 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0009_auto_20160312_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationorganizationuser',
            name='relation_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='relationorganizationuser',
            name='uuid_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allonsy_main.Account'),
        ),
        migrations.AlterField(
            model_name='relationorganizationuser',
            name='uuid_org',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='relationorganizationuser',
            name='uuid_user',
            field=models.CharField(max_length=100),
        ),
    ]
