# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-03 03:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allonsy_main', '0010_workflowitem_wf_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDocumentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_doc_item', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('uuid_doc_instance', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('wf_parent_set_name', models.CharField(max_length=64)),
                ('wf_sub_parent_set_name', models.CharField(max_length=64)),
                ('wf_item_sub_parent_disp_order', models.CharField(default='1', max_length=2)),
                ('wf_item_text', models.CharField(blank=True, max_length=256)),
                ('user_item_state', models.CharField(default='Off', max_length=16)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('wf_item_root_parent', models.ManyToManyField(related_name='root_parent', to='allonsy_main.WorkflowSet')),
                ('wf_item_sub_parent', models.ManyToManyField(related_name='immediate_parent', to='allonsy_main.WorkflowSet')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowDocumentMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_doc', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user_instance_nme', models.CharField(default='New form', max_length=256)),
                ('user_instance_state', models.CharField(choices=[('C', 'Created'), ('I', 'Edited and saved'), ('S', 'Submitted for review'), ('R', 'Reverted for edit'), ('A', 'Approved'), ('O', 'Saved as complete')], default='C', max_length=1)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('uuid_wf_edited_user', models.ManyToManyField(related_name='edited_by', to=settings.AUTH_USER_MODEL)),
                ('uuid_wf_user', models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='relationworkflowuserinstance',
            name='uuid_wf_edited_user',
        ),
        migrations.RemoveField(
            model_name='relationworkflowuserinstance',
            name='uuid_wf_set',
        ),
        migrations.RemoveField(
            model_name='relationworkflowuserinstance',
            name='uuid_wf_user',
        ),
        migrations.RemoveField(
            model_name='workflowdocuments',
            name='wf_item_root_parent',
        ),
        migrations.RemoveField(
            model_name='workflowdocuments',
            name='wf_item_sub_parent',
        ),
        migrations.DeleteModel(
            name='RelationWorkflowUserInstance',
        ),
        migrations.DeleteModel(
            name='WorkflowDocuments',
        ),
    ]
