# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-13 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0010_auto_20160312_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationorganizationuser',
            name='uuid_org',
        ),
        migrations.AddField(
            model_name='relationorganizationuser',
            name='uuid_org',
            field=models.ManyToManyField(to='allonsy_main.Organization'),
        ),
        migrations.RemoveField(
            model_name='relationorganizationuser',
            name='uuid_user',
        ),
        migrations.AddField(
            model_name='relationorganizationuser',
            name='uuid_user',
            field=models.ManyToManyField(to='allonsy_main.UserExtension'),
        ),
    ]
