# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-03 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0011_auto_20160802_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflowdocumentmaster',
            old_name='user_instance_nme',
            new_name='user_instance_name',
        ),
        migrations.RemoveField(
            model_name='workflowdocumentitem',
            name='uuid_doc_instance',
        ),
        migrations.AddField(
            model_name='workflowdocumentitem',
            name='uuid_doc',
            field=models.ManyToManyField(related_name='document_parent', to='allonsy_main.WorkflowDocumentMaster'),
        ),
    ]
