# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-13 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0011_auto_20160313_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationorganizationuser',
            name='uuid_user',
        ),
        migrations.AddField(
            model_name='relationorganizationuser',
            name='uuid_user',
            field=models.OneToOneField(default='1e3b0412-9edd-45fb-887f-642bd49572e0', on_delete=django.db.models.deletion.CASCADE, to='allonsy_main.UserExtension'),
        ),
    ]
