# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-05 00:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allonsy_main', '0012_auto_20160802_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='WFMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_meta_record', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_wf_item', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('wf_item_name', models.CharField(max_length=128)),
                ('wf_item_text', models.CharField(blank=True, max_length=256)),
                ('wf_item_status', models.CharField(choices=[('C', 'Created'), ('I', 'Edited and saved'), ('S', 'Submitted for review'), ('R', 'Reverted for edit'), ('A', 'Approved'), ('O', 'Saved as complete'), ('ON', 'Switch is on'), ('OFF', 'Switch is off'), ('Z', 'No status has been assigned')], default='Z', max_length=8)),
                ('wf_item_is_default', models.BooleanField(default=False)),
                ('wf_item_is_active', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='allonsy_main.WorkflowTree')),
                ('uuid_meta', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='allonsy_main.WFMetaData')),
                ('wf_item_owner', models.ManyToManyField(blank=True, related_name='owned_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='workflowset',
            name='wf_set_is_type',
            field=models.CharField(choices=[('X', 'No group set'), ('R', 'Nightly rounds'), ('D', 'On-call duty'), ('I', 'Room check-in'), ('O', 'Room check-out')], default='X', max_length=1),
        ),
    ]
