# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0012_auto_20160313_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='user_type',
            field=models.CharField(choices=[('X', 'Allonsy Developer'), ('Z', 'Allonsy Staff'), ('D', 'Account Developer'), ('S', 'Account Staff'), ('T', 'Student')], default='T', max_length=1),
        ),
    ]
