# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0013_userextension_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationorganizationuser',
            name='uuid_user',
        ),
        migrations.AddField(
            model_name='relationorganizationuser',
            name='uuid_user',
            field=models.ManyToManyField(default='1e3b0412-9edd-45fb-887f-642bd49572e0', to='allonsy_main.UserExtension'),
        ),
    ]
