# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-05 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0013_auto_20160804_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wfmetadata',
            name='uuid_meta_record',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
        ),
    ]
