# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-14 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0014_auto_20160412_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationorganizationuser',
            name='uuid_user',
            field=models.ManyToManyField(to='allonsy_main.UserExtension'),
        ),
    ]
