# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-14 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0015_auto_20160514_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationorganizationuser',
            name='relation_url',
            field=models.CharField(default='this-is-test', max_length=100),
            preserve_default=False,
        ),
    ]
