# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-05 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0015_auto_20160804_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wfmetadata',
            name='uuid_meta_record',
        ),
        migrations.RemoveField(
            model_name='workflowtree',
            name='uuid_meta',
        ),
        migrations.AddField(
            model_name='wfmetadata',
            name='uuid_workflowtree_record',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='allonsy_main.WorkflowTree'),
            preserve_default=False,
        ),
    ]
