# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-14 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0016_relationorganizationuser_relation_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='org_type_special',
            field=models.CharField(choices=[('A', 'Affiliation'), ('I', 'Interest'), ('V', 'Achievement'), ('X', 'No special class')], default='X', max_length=1),
        ),
    ]
