# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-30 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0017_auto_20160805_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtree',
            name='wf_item_proto_category',
            field=models.CharField(choices=[('CALL', 'On-call'), ('DUTY', 'On-duty'), ('ITSV', 'IT Service'), ('FASV', 'Facilities'), ('NONE', 'No status set')], default='NONE', max_length=8),
        ),
        migrations.AlterField(
            model_name='workflowtree',
            name='wf_item_name',
            field=models.CharField(max_length=1028),
        ),
        migrations.AlterField(
            model_name='workflowtree',
            name='wf_item_status',
            field=models.CharField(choices=[('C', 'Created'), ('I', 'Edited and saved'), ('S', 'Submitted for review'), ('R', 'Reverted for edit'), ('A', 'Approved'), ('O', 'Saved as complete'), ('ON', 'Switch is on'), ('OFF', 'Switch is off'), ('Z', 'No status has been assigned')], default='NONE', max_length=8),
        ),
    ]
