# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-13 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0018_auto_20160830_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treelocation',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='treelocation',
            name='uuid_account',
        ),
        migrations.RemoveField(
            model_name='treelocation',
            name='uuid_location',
        ),
        migrations.RemoveField(
            model_name='treeorganization',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='treeorganization',
            name='uuid_account',
        ),
        migrations.RemoveField(
            model_name='treeorganization',
            name='uuid_org',
        ),
        migrations.AlterModelManagers(
            name='organization',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='allonsy_main.Location'),
        ),
        migrations.AddField(
            model_name='organization',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='allonsy_main.Organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TreeLocation',
        ),
        migrations.DeleteModel(
            name='TreeOrganization',
        ),
    ]
