# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-16 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0018_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_aboutme',
            field=models.TextField(default='This user has not added any text!'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uuid_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allonsy_main.UserExtension'),
        ),
    ]
