# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-16 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0019_auto_20160516_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='uuid_user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
