# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-16 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0019_auto_20160912_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='uuid_account',
        ),
    ]
