# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-16 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0020_remove_organization_uuid_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='org_HasParent',
        ),
    ]
