# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-16 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0021_remove_organization_org_hasparent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_FullName',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_ShortName',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('A', 'Account'), ('U', 'University'), ('S', 'School or College'), ('D', 'Department'), ('O', 'Office'), ('L', 'Class or lecture'), ('E', 'Class or lecture section'), ('G', 'Group')], default='G', max_length=1),
        ),
    ]
