# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-16 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0021_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='user_role_name',
            field=models.CharField(default='TESTING', max_length=100),
        ),
    ]
