# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-16 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0022_userextension_user_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationorganizationuser',
            name='relation_is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
