# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-20 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0022_auto_20160916_0847'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='location',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_HasParent',
        ),
        migrations.RemoveField(
            model_name='location',
            name='uuid_account',
        ),
        migrations.AddField(
            model_name='location',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_abbreviation',
            field=models.CharField(max_length=8),
        ),
    ]
