# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-21 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0023_auto_20160920_1542'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='epoch',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='epoch',
            name='uuid_account',
        ),
        migrations.AddField(
            model_name='epoch',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='epoch',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='epoch',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='allonsy_main.Epoch'),
        ),
        migrations.AddField(
            model_name='epoch',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='epoch',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('A', 'Account'), ('C', 'Campus'), ('V', 'Village'), ('B', 'Building'), ('F', 'Floor'), ('S', 'Suite'), ('R', 'Room'), ('L', 'Location')], max_length=1),
        ),
    ]
