# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-16 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0023_relationorganizationuser_relation_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='user_personal_email_value',
            field=models.EmailField(default='test@test.org', max_length=100),
        ),
    ]
