# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-18 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0024_userextension_user_personal_email_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='user_personal_email_value',
            field=models.CharField(default='test@test.org', max_length=100),
        ),
    ]
