# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-02 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0024_auto_20160921_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='user_checkin_oncall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userextension',
            name='user_checkin_onduty',
            field=models.BooleanField(default=False),
        ),
    ]
