# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-12 17:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allonsy_main', '0025_auto_20161202_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteractionPayload',
            fields=[
                ('uuid_payload', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload_subject', models.TextField(blank=True, max_length=140)),
                ('payload_text', models.TextField(blank=True, max_length=1000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('uuid_sender', models.ManyToManyField(related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInteractionReadState',
            fields=[
                ('uuid_readstate', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_state', models.CharField(choices=[('O', 'New interaction'), ('I', 'Reviewed interaction'), ('X', 'Deleted interaction'), ('B', 'Blocked interaction'), ('F', 'Flagged as inappropriate')], max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('uuid_participant', models.ManyToManyField(related_name='readstate_participant', to=settings.AUTH_USER_MODEL)),
                ('uuid_payload', models.ManyToManyField(related_name='payload', to='allonsy_main.UserInteractionPayload')),
            ],
        ),
        migrations.CreateModel(
            name='UserInteractionRouting',
            fields=[
                ('uuid_routing', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('uuid_participant', models.ManyToManyField(related_name='routing_participant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInteractionThread',
            fields=[
                ('uuid_thread', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('C', 'Connection request'), ('R', 'Roommate request'), ('M', 'Message'), ('A', 'Alert'), ('N', 'Notification')], max_length=255)),
                ('interaction_name', models.CharField(blank=True, max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='userinteractionrouting',
            name='uuid_thread',
            field=models.ManyToManyField(related_name='routing_thread', to='allonsy_main.UserInteractionThread'),
        ),
        migrations.AddField(
            model_name='userinteractionpayload',
            name='uuid_thread',
            field=models.ManyToManyField(related_name='payload_thread', to='allonsy_main.UserInteractionThread'),
        ),
    ]
