# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-20 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0025_auto_20160517_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_1_PostalCode',
            field=models.CharField(default='TESTING', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_1_city_name',
            field=models.CharField(default='TESTING', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_1_country_id',
            field=models.CharField(default='US', max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_1_home_ApartmentNumber',
            field=models.CharField(default='TESTING', max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_1_home_street_name',
            field=models.CharField(default='TESTING', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_1_home_street_number',
            field=models.CharField(default='TESTING', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_1_hone_home_CountryCode',
            field=models.CharField(default='555', max_length=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_1_name',
            field=models.CharField(default='TESTING', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_1_personal_email_value',
            field=models.CharField(default='test@test.org', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_1_phone_home_value',
            field=models.CharField(default='TESTING', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_1_province_name',
            field=models.CharField(default='TESTING', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_2_PostalCode',
            field=models.CharField(default='TESTING', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_2_city_name',
            field=models.CharField(default='TESTING', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_2_country_id',
            field=models.CharField(default='US', max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_2_home_ApartmentNumber',
            field=models.CharField(default='TESTING', max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_2_home_street_name',
            field=models.CharField(default='TESTING', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_2_home_street_number',
            field=models.CharField(default='TESTING', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_2_name',
            field=models.CharField(default='TESTING', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_2_personal_email_value',
            field=models.CharField(default='test@test.org', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_2_phone_home_CountryCode',
            field=models.CharField(default='555', max_length=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_2_phone_home_value',
            field=models.CharField(default='TESTING', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_2_province_name',
            field=models.CharField(default='TESTING', max_length=100),
        ),
    ]
