# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-13 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0026_auto_20161212_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinteractionthread',
            name='interaction_type',
        ),
        migrations.AddField(
            model_name='userinteractionpayload',
            name='interaction_type',
            field=models.CharField(choices=[('C', 'Connection request'), ('R', 'Roommate request'), ('M', 'Message'), ('A', 'Alert'), ('N', 'Notification')], default='C', max_length=255),
        ),
    ]
