# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-20 16:09
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allonsy_main', '0027_auto_20160519_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('uuid_interaction', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('C', 'Send request to connect'), ('R', 'Send request to be roommate'), ('M', 'Send a message')], default='M', max_length=1)),
                ('interaction_status', models.CharField(choices=[('O', 'New interaction'), ('I', 'Reviewed interaction'), ('X', 'Deleted interaction'), ('B', 'Blocked interaction'), ('F', 'Flagged as inappropriate')], default='O', max_length=1)),
                ('interaction_subject', models.CharField(default='New message', max_length=100)),
                ('interaction_text', models.CharField(default='Hello!', max_length=1000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('interaction_sender', models.ManyToManyField(related_name='interaction_sender', to=settings.AUTH_USER_MODEL)),
                ('interaction_target', models.ManyToManyField(related_name='interaction_target', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 20, 16, 8, 59, 859702, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_edited',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 20, 16, 9, 9, 81651, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
