# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-14 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0027_auto_20161213_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinteractionpayload',
            name='uuid_relation',
            field=models.ManyToManyField(blank=True, related_name='relation', to='allonsy_main.RelationUserConnection'),
        ),
        migrations.AlterField(
            model_name='userinteractionpayload',
            name='interaction_type',
            field=models.CharField(choices=[('C', 'Connection request'), ('R', 'Roommate request'), ('M', 'Message'), ('A', 'Alert'), ('N', 'Notification')], max_length=255),
        ),
    ]
