# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-23 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0028_auto_20160520_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinteraction',
            name='interaction_direction',
            field=models.CharField(choices=[('R', 'Target of this interaction'), ('S', 'Sender of this interaction'), ('D', 'Dropped message')], default='D', max_length=1),
        ),
    ]
