# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-25 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0030_useralert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useralert',
            name='interaction_sender',
        ),
        migrations.RemoveField(
            model_name='useralert',
            name='interaction_target',
        ),
        migrations.DeleteModel(
            name='UserAlert',
        ),
    ]
