# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-25 23:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allonsy_main', '0031_auto_20160525_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_alert', models.UUIDField(default=uuid.uuid4)),
                ('interaction_direction', models.CharField(choices=[('R', 'Target of this interaction'), ('D', 'Dropped message')], default='D', max_length=1)),
                ('interaction_status', models.CharField(choices=[('O', 'New interaction'), ('I', 'Reviewed interaction'), ('X', 'Deleted interaction')], default='O', max_length=1)),
                ('interaction_type', models.CharField(choices=[('R', 'Reminder'), ('O', 'Overdue'), ('A', 'Alert')], default='A', max_length=1)),
                ('interaction_subject', models.CharField(default='New message', max_length=100)),
                ('interaction_text', models.CharField(default='Hello!', max_length=1000)),
                ('date_active_start', models.DateTimeField()),
                ('date_active_end', models.DateTimeField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('interaction_sender', models.ManyToManyField(related_name='alert_sender', to=settings.AUTH_USER_MODEL)),
                ('interaction_target', models.ManyToManyField(related_name='alert_target', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
