# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-26 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0032_useralert'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationUserConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('L', 'Personal connection'), ('M', 'Roommate connection'), ('G', 'Group connection')], max_length=1)),
                ('relation_status', models.CharField(choices=[('A', 'Active connection'), ('P', 'Pending connection'), ('R', 'Rejected connection'), ('D', 'Dropped connection')], max_length=1)),
                ('relation_expires', models.DateTimeField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('uuid_user_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uuid_user_1', to='allonsy_main.UserExtension')),
                ('uuid_user_2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uuid_user_2', to='allonsy_main.UserExtension')),
            ],
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('C', 'Connection request'), ('R', 'Roommate request'), ('M', 'Message')], default='M', max_length=1),
        ),
    ]
