# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-13 14:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0033_auto_20160526_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationorganizationuser',
            name='date_active',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 13, 14, 48, 6, 735468, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationorganizationuser',
            name='date_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 13, 14, 48, 18, 47874, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationorganizationuser',
            name='permission_is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationorganizationuser',
            name='permission_is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationorganizationuser',
            name='permission_is_faculty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationorganizationuser',
            name='permission_is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationorganizationuser',
            name='permission_is_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='relationorganizationuser',
            name='permission_template',
            field=models.CharField(default='TESTING', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userextension',
            name='user_type',
            field=models.CharField(choices=[('X', 'Allonsy Developer'), ('Z', 'Allonsy Staff'), ('D', 'Account Developer'), ('A', 'Account Admin'), ('S', 'Account Staff'), ('T', 'Student')], default='T', max_length=1),
        ),
    ]
