# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-14 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0034_auto_20160613_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_url_name',
            field=models.CharField(default=17, max_length=12),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_type_special',
            field=models.CharField(choices=[('A', 'Affiliation'), ('I', 'Interest'), ('V', 'Achievement'), ('R', 'Residence Life'), ('X', 'No special class')], default='X', max_length=1),
        ),
    ]
