# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-14 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0035_auto_20160614_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_url_name',
        ),
    ]
