# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-14 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0036_remove_account_account_url_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_url_name',
            field=models.CharField(default='test', max_length=24, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
