# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-14 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0037_auto_20160614_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_url_name',
            field=models.CharField(default=77, max_length=24, unique=True),
        ),
    ]
