# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-14 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0038_auto_20160614_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_url_name',
            field=models.CharField(default=14, max_length=24, unique=True),
        ),
    ]
