# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-14 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import tenant_schemas.postgresql_backend.base


class Migration(migrations.Migration):

    dependencies = [
        ('allonsy_main', '0039_auto_20160614_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='domain_url',
            field=models.CharField(default='127.0.0.1:8000', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='schema_name',
            field=models.CharField(default='public', max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='account_url_name',
            field=models.CharField(default=4, max_length=24, unique=True),
        ),
    ]
